/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NGOFunding } from "./NGOFunding";
export * as factories from "./factories";
export { NGOFunding__factory } from "./factories/NGOFunding__factory";
